#!/usr/bin/env python3
"""Generates the launcher icon - vector XML and legacy webp - from geometry.py.

  python3 tools/icon/make_icon.py            # write into app/src/main/res
  python3 tools/icon/make_icon.py --preview  # also drop a big PNG to look at

🔑 Run this after editing geometry.py. Nothing else regenerates it.
"""
import argparse, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import geometry as g

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.abspath(os.path.join(HERE, "..", "..", "app", "src", "main", "res"))

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!-- SPDX-License-Identifier: GPL-2.0-or-later -->
<!-- Copyright (C) 2026 Bill Kang -->
<!-- 🔑 GENERATED by tools/icon/make_icon.py from tools/icon/geometry.py - do not hand-edit. -->
"""

def rr_path(l, t, r, b, rad):
    """A rounded rectangle as SVG/VectorDrawable path data."""
    return (f"M{l+rad},{t} L{r-rad},{t} A{rad},{rad} 0 0 1 {r},{t+rad} "
            f"L{r},{b-rad} A{rad},{rad} 0 0 1 {r-rad},{b} "
            f"L{l+rad},{b} A{rad},{rad} 0 0 1 {l},{b-rad} "
            f"L{l},{t+rad} A{rad},{rad} 0 0 1 {l+rad},{t} Z")

def circle_path(cx, cy, r):
    return (f"M{cx},{cy-r} A{r},{r} 0 1 0 {cx},{cy+r} A{r},{r} 0 1 0 {cx},{cy-r} Z")

def vector(body):
    return (HEADER + '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            f'    android:width="108dp" android:height="108dp"\n'
            f'    android:viewportWidth="108" android:viewportHeight="108">\n{body}</vector>\n')

def write(path, text):
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    print("  ", os.path.relpath(path, os.path.dirname(RES)))

# ── background: a vertical gradient, drawn over the whole 108 canvas ──
def background_xml():
    body = ('    <path android:pathData="M0,0 L108,0 L108,108 L0,108 Z">\n'
            '        <aapt:attr xmlns:aapt="http://schemas.android.com/aapt" name="android:fillColor">\n'
            '            <gradient android:type="linear"\n'
            '                android:startX="0" android:startY="0"\n'
            '                android:endX="108" android:endY="108">\n'
            f'                <item android:offset="0" android:color="{g.BG_TOP}" />\n'
            f'                <item android:offset="1" android:color="{g.BG_BOT}" />\n'
            '            </gradient>\n'
            '        </aapt:attr>\n'
            '    </path>\n')
    return vector(body)

def _shapes(ink, accent, screen_fill):
    l, t, r, b = g.SCREEN
    s = g.SCREEN_STROKE
    out = []
    if screen_fill:
        out.append(f'    <path android:fillColor="{screen_fill}"\n'
                   f'        android:pathData="{rr_path(l, t, r, b, g.SCREEN_R)}" />\n')
    out.append(f'    <path android:strokeColor="{ink}" android:strokeWidth="{s}"\n'
               f'        android:fillColor="#00000000" android:strokeLineJoin="round"\n'
               f'        android:pathData="{rr_path(l, t, r, b, g.SCREEN_R)}" />\n')
    hbar, vbar = g.dpad_bars()
    for bar in (hbar, vbar):
        out.append(f'    <path android:fillColor="{ink}"\n'
                   f'        android:pathData="{rr_path(*bar, 1.4)}" />\n')
    for (cx, cy, rr) in g.buttons():
        out.append(f'    <path android:fillColor="{accent}"\n'
                   f'        android:pathData="{circle_path(cx, cy, rr)}" />\n')
    return "".join(out)

def foreground_xml():
    return vector(_shapes(g.INK, g.ACCENT, g.SCREEN_FILL))

def monochrome_xml():
    # 🔑 A themed icon is tinted as one flat colour, so the screen must NOT be filled - a filled
    #    screen would swallow the D-pad and buttons and leave a featureless blob.
    return vector(_shapes("#FF000000", "#FF000000", None))

# ── legacy raster ──
def raster(size, round_icon):
    from PIL import Image, ImageDraw
    SS = 4                      # supersample, then downscale - Pillow has no antialiased shapes
    px = size * SS
    scale = px / g.SAFE         # map the 72-unit safe square onto the icon
    def X(v): return (v - g.SAFE_MIN) * scale

    img = Image.new("RGBA", (px, px), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    # background plate
    top = tuple(int(g.BG_TOP[i:i+2], 16) for i in (1, 3, 5))
    bot = tuple(int(g.BG_BOT[i:i+2], 16) for i in (1, 3, 5))
    plate = Image.new("RGBA", (px, px))
    pd = ImageDraw.Draw(plate)
    for y in range(px):                      # the gradient, one row at a time
        f = y / max(px - 1, 1)
        pd.line([(0, y), (px, y)],
                fill=tuple(int(top[i] + (bot[i] - top[i]) * f) for i in range(3)) + (255,))
    mask = Image.new("L", (px, px), 0)
    md = ImageDraw.Draw(mask)
    if round_icon:
        md.ellipse([0, 0, px - 1, px - 1], fill=255)
    else:
        md.rounded_rectangle([0, 0, px - 1, px - 1], radius=int(px * 0.22), fill=255)
    img.paste(plate, (0, 0), mask)

    l, t, r, b = g.SCREEN
    d.rounded_rectangle([X(l), X(t), X(r), X(b)], radius=g.SCREEN_R * scale,
                        fill=g.SCREEN_FILL, outline=g.INK, width=max(1, round(g.SCREEN_STROKE * scale)))
    for bar in g.dpad_bars():
        d.rounded_rectangle([X(bar[0]), X(bar[1]), X(bar[2]), X(bar[3])],
                            radius=1.4 * scale, fill=g.INK)
    for (cx, cy, rr) in g.buttons():
        d.ellipse([X(cx - rr), X(cy - rr), X(cx + rr), X(cy + rr)], fill=g.ACCENT)
    return img.resize((size, size), Image.LANCZOS)

DENSITIES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--preview", action="store_true")
    a = ap.parse_args()

    print("vector:")
    write(os.path.join(RES, "drawable", "ic_launcher_background.xml"), background_xml())
    write(os.path.join(RES, "drawable", "ic_launcher_foreground.xml"), foreground_xml())
    write(os.path.join(RES, "drawable", "ic_launcher_monochrome.xml"), monochrome_xml())

    print("legacy raster:")
    for d, size in DENSITIES.items():
        for name, rnd in (("ic_launcher", False), ("ic_launcher_round", True)):
            out = os.path.join(RES, f"mipmap-{d}", f"{name}.webp")
            raster(size, rnd).save(out, "WEBP", lossless=True, quality=100)
            print("  ", os.path.relpath(out, os.path.dirname(RES)), f"{size}x{size}")

    if a.preview:
        p = "/tmp/icon_preview.png"
        from PIL import Image
        sheet = Image.new("RGBA", (512 + 512 + 30, 512), (24, 24, 28, 255))
        sheet.paste(raster(512, False), (0, 0))
        sheet.paste(raster(512, True), (542, 0))
        sheet.save(p)
        print("preview:", p)

if __name__ == "__main__":
    main()
